spring:
  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: liquibase/changelog.master.yml

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongok.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local